-- Restaurant Procurement Agent: schema (Phase 1)
-- Run once in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- All data seeded into these tables is DEMO / SIMULATED.

-- Ids are "generated by default" so a seed script may set them explicitly if it needs to.

create table if not exists suppliers (
  id                      bigint generated by default as identity primary key,
  name                    text not null unique,
  website                 text,
  contact_email           text,
  reliability_score       numeric(3,2) check (reliability_score between 0 and 1),  -- 0.00 to 1.00
  average_lead_time_days  integer check (average_lead_time_days >= 0),
  minimum_order_value     numeric(10,2) default 0,                                   -- currency, whole order
  notes                   text
);

create table if not exists inventory_items (
  id                   bigint generated by default as identity primary key,
  sku                  text not null unique,
  name                 text not null,
  category             text,
  unit                 text not null,                          -- the unit we count stock in: kg, L, each
  current_stock        numeric(12,3) not null default 0,
  safety_stock         numeric(12,3) not null default 0,       -- never want to drop below this
  current_supplier_id  bigint references suppliers(id),
  current_unit_price   numeric(12,4),                          -- price per `unit` from the current supplier
  lead_time_days       integer not null default 1,             -- order -> delivery, current supplier
  incoming_quantity    numeric(12,3) not null default 0,       -- already ordered, on its way
  incoming_date        date,
  updated_at           timestamptz not null default now()
);

create table if not exists usage_history (
  id                 bigint generated by default as identity primary key,
  inventory_item_id  bigint not null references inventory_items(id) on delete cascade,
  usage_date         date not null,
  quantity_used      numeric(12,3) not null check (quantity_used >= 0),
  unique (inventory_item_id, usage_date)
);
create index if not exists usage_history_item_date_idx on usage_history (inventory_item_id, usage_date);

create table if not exists supplier_products (
  id                     bigint generated by default as identity primary key,
  supplier_id            bigint not null references suppliers(id) on delete cascade,
  inventory_item_id      bigint not null references inventory_items(id) on delete cascade,
  supplier_product_name  text not null,
  unit_price             numeric(12,4) not null,   -- price of ONE selling unit (e.g. one case)
  unit                   text not null,            -- the selling unit: case, bag, tray, sack...
  pack_size              numeric(12,3) not null check (pack_size > 0),  -- inventory units inside one selling unit
  minimum_order_quantity numeric(12,3),                                  -- in selling units; NULL = not stated
  delivery_fee           numeric(10,2),                                  -- NULL = not stated (never assume 0)
  last_verified_at       timestamptz,
  source_type            text not null check (source_type in ('incumbent','historical','tavily_live','mock'))
);
-- Phase 4: web-discovered offers may not state a minimum order or a delivery fee. Unknown must stay NULL.
-- Upgrading a database created earlier? These are safe to re-run.
alter table supplier_products alter column minimum_order_quantity drop not null;
alter table supplier_products alter column minimum_order_quantity drop default;
alter table supplier_products alter column delivery_fee drop not null;
alter table supplier_products alter column delivery_fee drop default;
create unique index if not exists supplier_products_offer_uniq
  on supplier_products (supplier_id, inventory_item_id, supplier_product_name);
create index if not exists supplier_products_item_idx on supplier_products (inventory_item_id);
create index if not exists supplier_products_supplier_idx on supplier_products (supplier_id);

create table if not exists procurement_runs (
  id                     bigint generated by default as identity primary key,
  inventory_item_id      bigint not null references inventory_items(id) on delete cascade,
  required_quantity      numeric(12,3) not null,
  required_by            date,
  status                 text not null default 'pending'
                         check (status in ('pending','running','awaiting_approval','approved','rejected','failed')),
  predicted_stockout_date date,
  current_supplier_cost  numeric(12,2),
  recommended_supplier_id bigint references suppliers(id),
  recommended_cost       numeric(12,2),
  potential_saving       numeric(12,2),
  agent_rationale        text,
  created_at             timestamptz not null default now(),
  -- Phase 3: the agent run
  requirement            jsonb,                    -- snapshot of what Python calculated when the run was created
  recommendation         jsonb,                    -- the full structured recommendation
  agent_mode             text check (agent_mode in ('live','mock','fallback')),
  agent_session_id       text,                     -- ZooWork session id (live runs)
  error                  text,
  market_search          jsonb,                    -- Phase 4: what the live market search did (status, sources, errors)
  -- Phase 5: the human decision. status becomes 'approved' or 'rejected'; nothing is ever sent by the app.
  decided_at             timestamptz,
  decided_by             text,
  decision_note          text
);
alter table procurement_runs add column if not exists market_search    jsonb;
alter table procurement_runs add column if not exists decided_at       timestamptz;
alter table procurement_runs add column if not exists decided_by       text;
alter table procurement_runs add column if not exists decision_note    text;

-- Phase 5/7: RFQ draft on approve; optional send (mock or SMTP) only after a person clicks Send.
create table if not exists rfq_drafts (
  id                  bigint generated by default as identity primary key,
  procurement_run_id  bigint not null unique references procurement_runs(id) on delete cascade,
  supplier_name       text not null,
  supplier_id         bigint references suppliers(id),
  to_email            text,                         -- NULL when we have no contact address for the supplier
  subject             text not null,
  body                text not null,
  benchmark           jsonb,                        -- whether public price evidence was mentioned, and which
  status              text not null default 'draft' check (status in ('draft','sent','cancelled')),
  send_note           text,                         -- draft note, or what happened on send
  created_at          timestamptz not null default now(),
  sent_at             timestamptz,
  -- Phase 7: audit of the outbound message + optional SIMULATED supplier reply for the demo
  send_record         jsonb,
  supplier_reply      jsonb
);
alter table rfq_drafts add column if not exists send_record jsonb;
alter table rfq_drafts add column if not exists supplier_reply jsonb;
-- Upgrading a database created before Phase 3? These are safe to re-run.
alter table procurement_runs add column if not exists requirement      jsonb;
alter table procurement_runs add column if not exists recommendation   jsonb;
alter table procurement_runs add column if not exists agent_mode       text;
alter table procurement_runs add column if not exists agent_session_id text;
alter table procurement_runs add column if not exists error            text;

-- The agent activity timeline shown in the dashboard.
create table if not exists agent_events (
  id                  bigint generated by default as identity primary key,
  procurement_run_id  bigint not null references procurement_runs(id) on delete cascade,
  tone                text not null default 'info' check (tone in ('info','agent','success','error')),
  title               text not null,
  detail              text,
  payload             jsonb,
  created_at          timestamptz not null default now()
);
create index if not exists agent_events_run_idx on agent_events (procurement_run_id, id);

create table if not exists market_search_results (
  id                      bigint generated by default as identity primary key,
  procurement_run_id      bigint not null references procurement_runs(id) on delete cascade,
  supplier_name           text,
  product_name            text,
  raw_price               text,                    -- exactly as found on the page, e.g. "$43.20 / case"
  normalised_unit_price   numeric(12,4),           -- price per inventory unit, calculated in Python
  pack_size               numeric(12,3),
  minimum_order_quantity  numeric(12,3),
  delivery_information    text,
  source_url              text,
  source_domain           text,
  confidence              numeric(3,2) check (confidence between 0 and 1),
  raw_result              jsonb,
  created_at              timestamptz not null default now()
);
create index if not exists market_results_run_idx on market_search_results (procurement_run_id);

-- Keep inventory_items.updated_at fresh on every update.
create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists inventory_items_set_updated_at on inventory_items;
create trigger inventory_items_set_updated_at
  before update on inventory_items
  for each row execute function set_updated_at();

-- Security: switch on Row Level Security with NO policies. The public (anon) key can then
-- read nothing. Our Flask backend uses the service-role key, which bypasses RLS.
alter table suppliers              enable row level security;
alter table inventory_items        enable row level security;
alter table usage_history          enable row level security;
alter table supplier_products      enable row level security;
alter table procurement_runs       enable row level security;
alter table market_search_results  enable row level security;
alter table agent_events           enable row level security;
alter table rfq_drafts             enable row level security;
